# Generated by Django 4.1 on 2022-08-30 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descipcion", models.CharField(max_length=200)),
                ("imange", models.ImageField(upload_to="blog/imagenes")),
                ("fecha", models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
    ]
